services:
  - type: web
    name: wetlabs-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build --workspace=@wetlabs/api
    startCommand: cd apps/api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: RABBITMQ_URL
        sync: false
      - key: JWT_PRIVATE_KEY_BASE64
        value: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQzBjQ1FtbGVJekhPWUoKV0tudEsrZjU2VFpjUWNVdDFUcEFtcGFjVzFmMEUzQzd0akdpRjJIQlB3RFhQK0lwOERpNWduYzUxc2Q2UlM5NQpaVmthRFFMRkRoZ3hkY2xNMkFqQ2dmdnNkbjJrdWZrZmFwNzJuYnBRcnFLcVphckhab0orK2xyZlRnZlp3a2hOCnFBMUdTbjNwV3U5NFVFZU9ucGNhSjl5cCtOSVNjWTQ4UE5hL3IxNEwza0luaVBlaWV2OVRYWlRucjNkMkRFbU0KcUpwRy9aNUJKNDBTUGNLTU1xblpGT05MalJBOVJ4bWdsMm4vR1llR3V5KzEySDBhcDFvcUlOOTUwMk4zTjVzdApEbDJwclNVMEJ1UHQ3U0JtQWpYc1BrTXFjQm9ianF0Z3VMcFBqOVBodzFmSEY4S0JHbjY5NlBzMXE5MnNxZU5uCmlNMERQdVNsQWdNQkFBRUNnZ0VBUU9YS290UXE0TzVtY0hzaTF3cUJLM290VXA1WFFLWmVCc2x6SFRhZldrcTUKczlJU1pQWGE4NG5wRUFKS29vSGpyUmxYTDRib0JUcW9HaFlSSjVVQlo0V3J2dkpaM2hrZmdYSUYvYVVhaUtwWgpCMnN1Vkk0amFveDlOaU5OK3QwTVY0Wk5NOTdaWlFHRFJ1Y0lLejEwcnY5RmZUVUduNjI3dEMwZEtVYzBxMnZ2Cm5KdGRsNWJkUHFmUjQ4S0hSYzVEdFZHd1AxMkE5M3BiMnRJbFZrQWJ0MFA3WUR3RVY1c3ljWDF4cUYvS1Jkd0oKckI3dDVTVnJHaHRzSDExK3hKZlZkUFFFTlB6UFZKRCs5QzRWc2c2NzY0NjZ1T0VkQjJjSXBVc3lxaEUyc1VnVwpzbWxTU1UzRndOMXBCejFXaDdONTlMRnhZMktGeStzR3NDdERBd3pNT3dLQmdRRHlnRGg2NGxNalk4WHU4WHkwCnNxSnozT1ZqMWVQc0c5OVROQVJtbG1Cc085K2U5Y1hrazVNNndwS2lRa0JyL3BETTRHREVHbkc5RWRtVFRIUDIKRWd1MlhOM0gyaDJEY3lBam9Xdjh5V3lJR1lRR1FJUTZ2ZTZXRlluTGFyWkU3bnV0WTFhZ2kxVmxHYkorc0duZQpEOHNMMFpXemVkWDdrKzQwcXFETnJzN2NOd0tCZ1FDK2UzMDZ2Q2p6NWxkNUxjZEpIazAwRnF0a28rNm5LVE9uCmV2SE1pdkIydWRvbVlLTENsRmpBdHNZcDRqRG03c1Q5QnU1VkxUVENKZUF6dVRkMFkvZE1EOEdZTVBodVBmRkEKK3VKWDFxUTg2MDNZMVJjMGNjU0d1eDJJallOc2dlR2dLbEF0dGVuVEw1NmVIcFpUMFQ5Rk9GTENEWVRSWWdHRAowSmR4U3Jnd0F3S0JnSFJtdTdXd29idWhEc2VOUHhEMWxpa0xaVWl3eU1EeStCWFdLQzZlREJhbi9zVXNzQnJ5CkEzLzNHYSt0SVlNMUpJaFRROStkMmU2cGZNakpyL2Z6M1k5aHNFdFlGVWFkb2xXNEREL0E1OG5FaGEwQ2x2WWoKYVR5OWhmRVFmZ0ZFZ0RWUU02cklkdXNhbEtWZlJOSUV2ckFqb0RvUVIzaUZINWhFTnYvRDR5T3RBb0dBVDZIRQptcmRxejN3dWVZUi8yYnVIUHcxekhhSEM5Yk10MndoMDZiUDBEMDVuT3NBUGl4VUZmWnRyZ0xzRkFxWXpTQ3lMCm1xUkplQmpwZi9ZZ2p0SHo0cUo3cHFwaVVZUW54YWljMDJmeVJWMkJyL0oxdndFSXplS1AyRFNCQ3UzSmEzSUYKRHZjTUI3UFN0ZnZIa01iYmtvNlhXblRZWDhoL0phSWdqY1pVOWcwQ2dZQUZtTUJOd2hTdUJqbkdBWFFUd3RPYwpjakt4Tm5rbFpoL0dWQ0kxcFJJb05nS3RVZjAvS3Z0cE03MjlhSmt6cE5GQmtmdEUyUWFuNHJ4NGFpcEFJQ3ZwCnZldDRaekhGcVlOSUZRbnRsdG01aWxOa0loTTR2MTNmV0NNSWhDQTFBZ1M1NjIvMXpUVlRkaGp5WTk0SkFXaXkKb3EwSVBQVkpQVXVHUDVKek1zNXUyQT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
      - key: JWT_PUBLIC_KEY_BASE64
        value: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0SEFrSnBYaU14em1DVmlwN1N2bgorZWsyWEVIRkxkVTZRSnFXbkZ0WDlCTnd1N1l4b2hkaHdUOEExei9pS2ZBNHVZSjNPZGJIZWtVdmVXVlpHZzBDCnhRNFlNWFhKVE5nSXdvSDc3SFo5cExuNUgycWU5cDI2VUs2aXFtV3F4MmFDZnZwYTMwNEgyY0pJVGFnTlJrcDkKNlZydmVGQkhqcDZYR2lmY3FmalNFbkdPUER6V3Y2OWVDOTVDSjRqM29uci9VMTJVNTY5M2RneEpqS2lhUnYyZQpRU2VORWozQ2pES3AyUlRqUzQwUVBVY1pvSmRwL3htSGhyc3Z0ZGg5R3FkYUtpRGZlZE5qZHplYkxRNWRxYTBsCk5BYmo3ZTBnWmdJMTdENURLbkFhRzQ2cllMaTZUNC9UNGNOWHh4ZkNnUnArdmVqN05hdmRyS25qWjRqTkF6N2sKcFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
      - key: JWT_EXPIRES_IN
        value: 3600
      - key: MSISDN_PEPPER
        value: 64bc8111a21523b26e8fb544d17196acffaba0619be7a998bb96b1e492f0df68
      - key: AT_USSD_HMAC_SECRET
        value: dummy_AT_hmac_secret
      - key: INTERNAL_API_KEY
        value: eceb056c7444a01effe2a4094557dedcdac57099a18c4f085cbfd4665d1e0177
      - key: CORS_ORIGIN
        value: "*"
      - key: AT_API_KEY
        value: ""
      - key: AT_USERNAME
        value: sandbox
      - key: SENDGRID_API_KEY
        value: ""
      - key: SENTINEL_HUB_CLIENT_ID
        value: ""
      - key: SENTINEL_HUB_CLIENT_SECRET
        value: ""
      - key: S3_BUCKET
        value: wetlabs-photos
      - key: S3_ENDPOINT
        value: https://s3.amazonaws.com
      - key: S3_ACCESS_KEY
        value: ""
      - key: S3_SECRET_KEY
        value: ""
